const GET_SPLYT_DRIVERS_START = 'GET_SPLYT_DRIVERS_START';
const GET_SPLYT_DRIVERS_SUCCESS = 'GET_SPLYT_DRIVERS_SUCCESS';
const GET_SPLYT_DRIVERS_ERROR = 'GET_SPLYT_DRIVERS_ERROR';

export { GET_SPLYT_DRIVERS_START, GET_SPLYT_DRIVERS_SUCCESS, GET_SPLYT_DRIVERS_ERROR };
